---

- name: This is a playbook for linux user management
  hosts: "{{ target_servers }}"
  vars:
    user_name_1: "{{ user_name }}"
    grp_perm_1: "{{ groups_name }}"
    action_is:  "{{ action }}"
  tasks:
  - import_role:
      name: user_operations
    vars:
       user_name_role:  "{{ user_name_1 }}"
       grp_perm_role: "{{ grp_perm_1 }}" 
       action_role:  "{{ action_is }}" 
    become: true
