---
tasks:
- name: Add user to the system
  user:
    name: {{ user_name_role }}
    generare_ssh_keys: yes
    password: 'DUMMY_password'
    shell: /bin/bash
    system: no 
    groups: {{ grp_perm_role }}
    append: yes 
  command: chage -d 0 {{ user_name_role }}
