---
name: Add users to the system
include: addusers.yml
when: action == "add_user"

name: Delete users from the system
include: delusers.yml
when: action == "del_user"

name: Disable users from the system
include: mod_users.yml
when: action == "disable_user"
