---

- name: Add users to the system
  include: add_user.yml
  when: ' action_role  == "add_user"'

- name: Delete users from the system
  include: del_user.yml
  when: ' action_role == "del_user"'

- name: Disable users from the system
  include: disable_user.yml
  when: ' action_role  == "disable_user"'
